drop table if exists "informix".alcatel_e10 ;
create table "informix".alcatel_e10 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    origfilename varchar(32,1),
    ticketnum integer,
    msctype char(1),
    billingind char(1),
    calltype char(1),
    efficiencyind char(1),
    terminationtype char(1),
    unefficiencyind char(1),
    callorigind char(1),
    chargingind char(1),
    reqteleservice integer,
    reqbearerserv integer,
    circuitalloctm datetime year to second,
    unitquantity integer,
    cl_start_dt_srvr datetime year to second,
    imei varchar(20,1),
    inss varchar(20,1),
    linkinfoprfx integer,
    linkinfo char(18),
    mobsubid varchar(32,1),
    mscidprfx integer,
    mscid char(18),
    callpartidprfx varchar(9,1),
    callpartid char(18),
    mslocmcc integer,
    mslocmnc integer,
    msloclac integer,
    mslocci integer,
    mslocprfx integer,
    mslocext char(18),
    channeltype integer,
    speechversion integer,
    linkidprfx integer,
    linkid varchar(18,1),
    fixednetinfo varchar(32,1),
    cl_start_dt datetime year to second not null ,
    utctimeoffset integer,
    circuitdealloctm datetime year to second,
    callfwddest varchar(32,1)
  );

