drop table if exists "informix".emer_cdr_chg ;
create table "informix".emer_cdr_chg 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_type decimal(2,0) not null ,
    usage_id decimal(17,0),
    orig_usage_id decimal(17,0),
    supplier_id decimal(17,0),
    serv_type_id decimal(17,0),
    account_id decimal(17,0),
    service_id decimal(17,0),
    tariff_id varchar(18) not null ,
    time_band_id varchar(18),
    tariff_desc varchar(129),
    suppl_desc varchar(129),
    currency_id decimal(3,0),
    tax_id decimal(3,0),
    servid_type_cd char(2),
    charge_id varchar(255) not null ,
    source_num varchar(128),
    dest_num varchar(128),
    term_num varchar(128),
    date_start char(10),
    time_start char(8),
    date_end char(10),
    time_end char(8),
    unit_type_id decimal(3,0) not null ,
    units decimal(8,0) not null ,
    data_download decimal(17,0),
    data_upload decimal(17,0),
    rated_amt decimal(16,7),
    charged_amt decimal(16,7),
    invoiced_amt decimal(16,7),
    drcr char(2) not null ,
    pack_plan_id decimal(17,0),
    serv_plan_id decimal(17,0),
    rate_card_id decimal(17,0),
    bolton_pl_id decimal(17,0),
    prod_rcard_id decimal(17,0),
    serv_feat_type decimal(17,0),
    pack_subs_id decimal(17,0),
    serv_subs_id decimal(17,0),
    bolton_subs_id decimal(17,0),
    feat_subs_id decimal(17,0),
    pack_period decimal(17,0),
    serv_period decimal(17,0),
    bolton_period decimal(17,0),
    servfeat_period decimal(17,0),
    session_id varchar(50),
    orig_ip_addr varchar(22),
    service_num varchar(255),
    start_dt datetime year to second,
    end_dt datetime year to second,
    add_info_1 varchar(129),
    add_info_2 varchar(129),
    add_info_3 varchar(129),
    add_info_4 varchar(129),
    add_info_5 varchar(129),
    add_info_6 varchar(129),
    add_info_7 varchar(129),
    add_info_8 varchar(129),
    add_info_9 varchar(129),
    add_info_10 varchar(129),
    add_info_11 varchar(129),
    add_info_12 varchar(129),
    add_info_13 varchar(129),
    add_info_14 varchar(129),
    add_info_15 varchar(129),
    add_info_16 varchar(129),
    add_info_17 varchar(129),
    add_info_18 varchar(129),
    add_info_19 varchar(129),
    add_info_20 varchar(129)
  );

