drop table if exists "informix".inmarsat_cdr ;
create table "informix".inmarsat_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    invoice_num varchar(20),
    customer_nm varchar(80),
    start_date varchar(8) not null ,
    start_time varchar(8) not null ,
    country_code varchar(3),
    destination varchar(63),
    region varchar(20),
    charge_num decimal(16,0),
    product_desc varchar(80),
    number_from varchar(63),
    call_type varchar(3) not null ,
    service_code varchar(2),
    cost_alloc_cd varchar(30),
    namorg varchar(35),
    cdkind varchar(20),
    cdfaci varchar(20),
    numwrd decimal(15,0),
    bitnum decimal(15,0),
    orig_cntry varchar(50),
    orig_zone varchar(10),
    prod_code varchar(18),
    var_code varchar(6),
    ip_address varchar(30),
    term_desc varchar(25),
    imei varchar(30),
    list_price decimal(16,3),
    session_id varchar(50),
    subsc_nmme varchar(50),
    contract varchar(10),
    scap_id varchar(25),
    vehicle_id varchar(15),
    sess_cl_date varchar(8),
    sess_cl_time varchar(8),
    numwrd_up decimal(6,0),
    numwrd_down decimal(6,0),
    bitnum_up decimal(15,0),
    bitnum_down decimal(15),
    num_inbundle decimal(15,2),
    num_outbundle decimal(15,2),
    bit_inbundle decimal(25,2),
    bit_outbundle decimal(25,2),
    chg_inbundle decimal(19,3),
    chg_outbundle decimal(19,3),
    cdcurr char(3),
    overage_amt decimal(10,0),
    cdr_type varchar(10)
  );

