drop table if exists "informix".jpo_data ;
create table "informix".jpo_data 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    detail_id varchar(20),
    icc_id varchar(50),
    msisdn varchar(50),
    imsi varchar(50),
    acct_id varchar(20),
    bill_flag char(1),
    bill_cycle varchar(20),
    sim_state integer,
    serv_type varchar(50),
    rate_plan_id varchar(20),
    rate_zone_id varchar(20),
    offpk_usage_fl char(1),
    record_dt varchar(20),
    usage_tot decimal(15,0),
    usage_up decimal(15,0),
    usage_down decimal(15,0),
    usage_round decimal(15,0),
    apn varchar(100),
    ip_addr varchar(100),
    op_network varchar(20),
    rec_open_tm varchar(20),
    session_dur decimal(15,0),
    rec_seq_num varchar(50),
    chg_id varchar(20),
    sess_cl_cause varchar(20),
    tap_code varchar(20),
    op_acct_id varchar(200),
    pl_version_id varchar(20),
    stream_id varchar(200),
    cgi varchar(200),
    sai varchar(200),
    rai varchar(200),
    tai varchar(200),
    ecgi varchar(200),
    lai varchar(200),
    serv_sgsn varchar(200),
    all_tech_type varchar(200)
  );

