drop table if exists "informix".m2_cdr_chg ;
create table "informix".m2_cdr_chg 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_type integer not null ,
    supplier_id integer not null ,
    tariff_id varchar(16) not null ,
    description varchar(128) not null ,
    tax_id integer not null ,
    serv_type_cd char(2) not null ,
    chg_id varchar(255) not null ,
    destin_num varchar(20),
    term_num varchar(20),
    start_dt datetime year to second,
    end_dt datetime year to second,
    unit_type_id integer not null ,
    unit_qty integer not null ,
    charge_amt decimal(16,7) not null ,
    inv_amt decimal(16,7) not null ,
    drcr char(2) not null ,
    rate_plan_id varchar(128),
    pack_plan_id varchar(128),
    pack_sub_id varchar(128),
    add_info1 varchar(128),
    add_info2 varchar(128),
    add_info3 varchar(128),
    add_info4 varchar(128),
    add_info5 varchar(128),
    add_info6 varchar(128),
    add_info7 varchar(128),
    add_info8 varchar(128),
    add_info9 varchar(128),
    add_info10 varchar(128),
    add_info11 varchar(128),
    add_info12 varchar(128),
    add_info13 varchar(128),
    add_info14 varchar(128),
    add_info15 varchar(128),
    add_info16 varchar(128),
    add_info17 varchar(128),
    add_info18 varchar(128),
    add_info19 varchar(128),
    add_info20 varchar(128),
    service_num varchar(64)
  );

