drop table if exists "informix".obs_cdr_chg ;
create table "informix".obs_cdr_chg 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_code char(2) not null ,
    bus_arrange varchar(20),
    invoice_date varchar(8),
    doc_ref_num varchar(12),
    line_seq integer,
    row_num integer,
    service_num varchar(20) not null ,
    record_type char(1),
    line_type char(1),
    call_type_code varchar(10),
    call_duration decimal(10,0),
    call_meter integer,
    service_num1 varchar(63),
    service_num2 varchar(63),
    ex_prod_rate decimal(12,0),
    filler decimal(12,0),
    to_area varchar(20),
    number_label varchar(30),
    start_date char(8) not null ,
    end_date char(8),
    start_time char(8),
    period_desc varchar(10),
    explanation varchar(30),
    item_ref_num varchar(10),
    prod_bill_id varchar(10),
    bill_element varchar(10),
    ebs_trans_type char(2),
    class_code varchar(10),
    base_rate decimal(13,2),
    gros_excl_gst decimal(13,2),
    amt_disc decimal(13,2),
    amt_excl_gst decimal(13,2) not null ,
    amt_gst decimal(13,2),
    amt_incl_gst decimal(13,2),
    event_id varchar(20),
    pricing_ind char(1),
    inv_date varchar(10),
    description varchar(90),
    time_amt decimal(13,2),
    vol_amt decimal(13,2),
    volume decimal(10,0),
    service_loc1 varchar(30),
    service_loc2 varchar(30),
    service_loc3 varchar(30),
    service_loc4 varchar(30),
    cug_id integer,
    trans_desc varchar(50),
    text1 varchar(20),
    text2 varchar(20),
    text3 varchar(20),
    text4 varchar(20),
    text5 varchar(20),
    unit_rate decimal(17,9),
    purch_order varchar(20),
    trans_type_desc varchar(90),
    serv_arr_type char(4),
    data_serv_data varchar(80),
    pcms_code_a char(8),
    pcms_code_b char(3),
    speed1 decimal(10,0),
    speed2 decimal(10,0),
    filler1 char(1),
    order_item_qty varchar(10),
    generic_qty decimal(10,0),
    prod_offer_nm varchar(80),
    filler2 decimal(11,0),
    ins_pay_num char(4),
    oc_trans_desc varchar(100),
    dir_entry_desc varchar(80),
    obs_trans_desc varchar(90),
    chg_start_dt datetime year to second,
    chg_end_dt datetime year to second,
    srvc_type_desc varchar(35),
    unit_desc varchar(15),
    call_trans_cnt varchar(12),
    answer_num varchar(30),
    disc_plan_desc varchar(55),
    rate_desc varchar(12),
    extract_to_date varchar(10)
  );

