drop table if exists "informix".oetmp ;
create table "informix".oetmp 
  (
    ordrid integer not null ,
    abnregdate date,
    abrno varchar(254),
    acnregdate date,
    chkpobox varchar(254),
    chkstreet varchar(254),
    chkthreeyears varchar(254),
    heard varchar(254),
    employmentstatus varchar(254),
    employmentlength varchar(254),
    employer_name varchar(254),
    primry varchar(254),
    primarytype varchar(254),
    secondry varchar(254),
    secondarytype varchar(254),
    additional varchar(254),
    additionaltype varchar(254),
    creditdefault varchar(254),
    namechange varchar(254),
    lastapplied varchar(254),
    paymethod varchar(254),
    existingnumber varchar(254),
    creditscore varchar(254),
    plannarr varchar(254),
    mobilenumber varchar(254),
    lcsp varchar(254),
    lcspnumber varchar(254),
    dob date,
    pcn varchar(254),
    handset varchar(254),
    imei varchar(254),
    paytypecode varchar(254),
    strtypecode varchar(254),
    billsendoption varchar(254),
    accountname varchar(254),
    accountnumber varchar(254),
    expirydate date,
    paytypeselectedval varchar(254),
    password varchar(254),
    unlimited char(1) 
        default 'N' not null ,
    cred_chk_id integer,
    crchk_id varchar(40),
    crchk_decision varchar(20),
    crchk_status varchar(20),
    crchk_start_time datetime year to second,
    crchk_last_updt datetime year to second,
    
    check (unlimited IN ('Y' ,'N' )) constraint "informix".yes_no
  );

