drop table if exists "informix".openet_cdr ;
create table "informix".openet_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_type char(1),
    offer_id varchar(20),
    group_id varchar(20),
    subscription_id varchar(100),
    balance_id varchar(200),
    offer_entitle_name varchar(100),
    msisdn varchar(20),
    imsi varchar(20),
    subscriber_id varchar(20),
    subscriber_type varchar(20),
    charge_type char(1),
    record_open_time varchar(20),
    record_close_time varchar(20),
    session_id varchar(200),
    sgsn_ip_address varchar(20),
    mccmnc varchar(20),
    ggsn_address varchar(20),
    ggsn_charge_id varchar(20),
    apn varchar(100),
    rating_group varchar(5),
    service_id varchar(20),
    rat_type varchar(5),
    user_location varchar(20),
    ms_timezone varchar(10),
    is_roaming char(1),
    zone varchar(20),
    cc_time varchar(10),
    cc_total_octets varchar(10),
    cc_input_octets varchar(10),
    cc_output_octets varchar(10),
    termination_cause varchar(10),
    counter_final_val varchar(50),
    rated_val_pre_tax varchar(20),
    rated_val_post_tax varchar(20),
    user_equip_type varchar(20),
    user_equip_value varchar(20),
    balance_impct_name varchar(50),
    request_number varchar(5),
    imei varchar(20),
    other_party_addr varchar(100),
    classification varchar(200),
    direction_type varchar(10),
    zone_called varchar(20),
    cc_service_units varchar(20),
    request_type varchar(200),
    offer_name varchar(100),
    result_code varchar(100),
    vlrid varchar(100),
    glid varchar(100),
    idd_code varchar(80),
    idd_desc varchar(150)
  );

