drop table if exists "informix".opt_cdr ;
create table "informix".opt_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    rec_type char(2) not null ,
    sp_cdr_id decimal(12,0) not null ,
    acc_number char(14) not null ,
    ext_id char(24) not null ,
    ext_id_type integer,
    point_orig char(24),
    point_targ char(24),
    jurisdiction integer,
    trans_dt datetime year to second not null ,
    bill_class integer,
    type_id_usg integer not null ,
    element_id integer,
    primary_units decimal(10,0) not null ,
    comp_status integer,
    latitude char(8),
    longitude char(8),
    orig_desc char(32),
    targ_desc char(32),
    rate_period char(1),
    rated_units decimal(10,0),
    second_units decimal(10,0),
    third_units decimal(10,0),
    file_id decimal(10,0),
    orig_extr_seq integer,
    amount decimal(8,3) not null ,
    rate_class integer,
    prov_class integer,
    prov_id integer,
    curr_code integer,
    equip_typecode integer,
    class_of_svc integer,
    rate_unit_type integer,
    dist_band_id integer,
    zone_class integer,
    cdr_status integer
  );

