drop table if exists "informix".optus_inv ;
create table "informix".optus_inv 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    org_unit_nm varchar(80),
    bill_year varchar(10),
    bill_period integer,
    om_serv_id varchar(80),
    feature_type varchar(80),
    feature_val varchar(20),
    value_desc varchar(120),
    unit_measure varchar(80),
    period_start date not null ,
    period_end date,
    period_id varchar(10),
    contract_tm varchar(20),
    period_age varchar(10),
    product_nm varchar(20),
    charge_class varchar(80),
    bill_days integer,
    inv_position varchar(10),
    quantity integer not null ,
    unitchg_amt decimal(15,3) not null ,
    rated_amt decimal(15,3) not null ,
    sold_ft_id varchar(10),
    reference varchar(10),
    date_insert varchar(30),
    cust_ref varchar(80),
    zone varchar(20),
    disc_value varchar(20),
    invoice_id varchar(20),
    adv_period integer,
    adv_year varchar(10),
    invoice_ref varchar(80),
    rate_plan_id varchar(20),
    rate_plan_nm varchar(80)
  );

