drop table if exists "informix".orcon_cdr ;
create table "informix".orcon_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    seq_num varchar(100,32) not null ,
    record_id varchar(32) not null ,
    record_type varchar(10) not null ,
    call_type char(1) not null ,
    orig_num varchar(63,10),
    orig_dial_digit varchar(63,10),
    terminat_num varchar(63,10),
    forward_fr_dn varchar(63,10),
    ani_auto_num varchar(63,10),
    start_time datetime year to second not null ,
    cl_answer_tm varchar(20),
    cl_rel_tm varchar(20),
    cl_duration integer not null ,
    attempt_ind integer,
    rel_cause integer,
    ini_rel_cause integer,
    reason_for_rel integer,
    origin_address integer,
    ingr_sign_type integer,
    egr_sign_type integer,
    cl_feature integer,
    mdr_origin varchar(20),
    mdr_termin varchar(20),
    acct_code varchar(80),
    author_code varchar(80),
    addi_cdr_ref varchar(80),
    filename varchar(120),
    device varchar(80),
    filetype varchar(80),
    version varchar(80),
    create_dt varchar(20),
    cdrcount integer,
    close_dt varchar(20)
  );

