drop table if exists "informix".ows_mur ;
create table "informix".ows_mur 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    switch_type char(2),
    record_type varchar(5),
    billable_num varchar(30),
    calling_num varchar(30),
    called_num varchar(30),
    imsi_num varchar(30),
    call_dt varchar(20),
    call_duration decimal(10),
    call_direction char(1),
    call_product varchar(15),
    fl_internati char(1),
    suppl_serv varchar(5),
    call_type varchar(5),
    origin varchar(15),
    destination varchar(15),
    fl_obroaming char(1),
    opt_use_num varchar(30),
    orig_country varchar(30),
    fl_success char(1),
    completion_dt varchar(20),
    service_class char(1),
    service_id decimal(10),
    start_dt varchar(20),
    end_dt varchar(20),
    vol_downlink decimal(12),
    vol_uplink decimal(12),
    apn varchar(30),
    content_chg char(11),
    content_gst char(11),
    x190_chg char(10),
    x190_dur char(5),
    chg_amt decimal(13,2),
    gst_amt decimal(13,2)
  );

