drop table if exists "informix".people_b2b_req ;
create table "informix".people_b2b_req 
  (
    ntwtransid integer not null ,
    trx_seq_code char(10) not null ,
    service_num char(10),
    action_code char(6) not null ,
    trx_apply_date char(10) not null ,
    rate_plan char(6),
    service_acc char(10),
    sim_no char(20),
    port_acc_no char(20),
    dob date,
    street_no integer,
    street_type char(3),
    street_suff char(1),
    sub_addr_no integer,
    sub_addr_type char(5),
    street_name varchar(32),
    suburb varchar(32),
    state char(3),
    pcode char(4),
    old_sp varchar(32),
    req_install_date date,
    reloc_no char(10),
    contract_term integer,
    serv_type char(1) not null ,
    modem_type char(10),
    modem_dely_addr varchar(32),
    modem_suburb varchar(32),
    modem_state varchar(32),
    modem_postcode varchar(32),
    paging_msg varchar(60),
    vm_node char(10),
    home_zone varchar(20),
    call_hold char(1),
    displ_cli char(1)
  );

