drop table if exists "informix".qualcomm_cdr ;
create table "informix".qualcomm_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    rln integer,
    orig_file varchar(64,1),
    orig_rec_num integer,
    call_id varchar(32,1),
    conn_ref_id varchar(32,1),
    event_time datetime year to second,
    call_dir char(1),
    imsi char(15),
    tmsi varchar(32,1),
    dial_num_type smallint,
    dial_num_plan smallint,
    dial_pi smallint,
    dial_si smallint,
    dial_digits varchar(32,1),
    called_num_type smallint,
    called_num_plan smallint,
    called_pi smallint,
    called_si smallint,
    called_num varchar(32,1),
    calling_num_type smallint,
    calling_num_plan smallint,
    calling_pi smallint,
    calling_si smallint,
    calling_num varchar(32,1),
    gsso varchar(32,1),
    utpr smallint,
    slotted smallint,
    se_address integer,
    trunk_dir char(1),
    utloc_lat decimal(12,3),
    utloc_long decimal(12,3),
    utloc_alt integer,
    utloc_acc integer,
    utloc_time datetime year to second,
    flsatid smallint,
    flbeamid integer,
    gsfwdfreq integer,
    gsrevfreq integer,
    imei char(16),
    call_type char(1),
    mscid integer,
    mobstart_rtd integer,
    roamer_flag char(1),
    ut_type smallint,
    spid_mcc integer,
    spid_mnc integer,
    airlink_start_tm datetime year to second,
    setup_rectime datetime year to second,
    channel_ass_tm datetime year to second,
    setup_features varchar(20,1),
    rlsat_id smallint,
    rlbeam_id smallint,
    airlink_end_tm datetime year to second,
    event_tm datetime year to second,
    surviving varchar(32,1),
    release_reas smallint,
    revlink_qual smallint,
    fwdlink_qual smallint,
    callrevlink_qual smallint,
    callfwdlink_qual smallint,
    relrec_tm datetime year to second,
    callcomp_tm datetime year to second,
    cl_start_dt datetime year to second,
    trunk_con_durn decimal(12,3),
    utloc_lac integer,
    feature_desc char(2),
    dest_digits varchar(32,1)
  );

