drop table if exists "informix".srvc_qualification ;
create table "informix".srvc_qualification 
  (
    id serial not null ,
    status varchar(20) 
        default 'Active' not null ,
    address lvarchar(1000),
    address_ref integer,
    available_services lvarchar(30000),
    contact_code char(10),
    partner_code char(10),
    template_id integer,
    service_class_id varchar(20),
    service_class varchar(254),
    address1 varchar(100),
    address2 varchar(100),
    suburb varchar(64),
    city varchar(64),
    state varchar(64),
    postcode varchar(10),
    country_code char(2),
    country_narr varchar(32),
    dpid integer,
    co varchar(64),
    build_name varchar(32),
    build_location varchar(32),
    build_desc varchar(128),
    build_nmbr varchar(32),
    build_code varchar(20),
    level_nmbr varchar(32),
    level_nmbr_sfx char(1),
    level_type varchar(10),
    locality varchar(32),
    lot_nmbr varchar(10),
    po_box_nmbr varchar(10),
    po_box_nmbr_pfx varchar(10),
    po_box_nmbr_sfx varchar(10),
    po_box_type varchar(12),
    post_code varchar(6),
    sort_plan varchar(10),
    state_code char(3),
    street_name varchar(32),
    street_nmbr1 varchar(10),
    street_nmbr_sfx1 varchar(10),
    street_nmbr2 varchar(10),
    street_nmbr_sfx2 varchar(10),
    street_type varchar(5),
    street_type_sfx varchar(10),
    unit_nmbr varchar(10),
    unit_nmbr_sfx varchar(10),
    unit_nmbr2 varchar(5),
    unit_nmbr_sfx2 char(1),
    unit_type varchar(10),
    grp_did char(1) 
        default 'N' not null ,
    barcode varchar(20),
    alt_postcode varchar(6),
    alt_locality varchar(32),
    alt_street_name varchar(32),
    alt_street_type varchar(5),
    alt_str_type_sfx varchar(10),
    street_name2 varchar(32),
    street_type2 varchar(5),
    street_type_sfx2 varchar(10),
    finding_name1 varchar(40),
    finding_name2 varchar(40),
    finding_title varchar(12),
    created_tm datetime year to second 
        default current year to second not null ,
    created_by varchar(18,10) 
        default user not null ,
    last_updated datetime year to second 
        default current year to second not null ,
    updated_by varchar(18,10) 
        default user not null ,
    
    check (status IN ('Active' ,'Pending' ,'Inactive' )) constraint "informix".status_srvcq
  );

