drop table if exists "informix".st_mobroam ;
create table "informix".st_mobroam 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    rec_type char(1),
    file_type char(1),
    copy_book_type char(1),
    traffic_type char(2),
    nw_svc_type char(2),
    nw_svc_id varchar(21),
    nw_svc_line_num char(4),
    date_of_call char(8),
    time_of_call char(6),
    destination_abbr char(3),
    route_code varchar(6),
    called_num varchar(24),
    calling_num varchar(21),
    exchange_code char(2),
    destination_ind char(1),
    creation_ind char(1),
    counter_ind char(1),
    ref_num varchar(8),
    loc_outpymt_ind char(1),
    total_charge varchar(11),
    exchg_serial_num varchar(17),
    paying_ac varchar(8),
    indicator_area varchar(40),
    corp_ind char(1),
    cinod_ind char(1),
    filler varchar(12),
    pr12_rate_code varchar(2),
    pr12_roam_svc_ind char(1),
    pr12_direct_code char(1),
    pr12_chrg_duration varchar(9),
    pr12_chrg_bytes varchar(11),
    pr12_reinput_ind char(1),
    pr12_operator varchar(26),
    pr12_cf_ind varchar(1),
    pr12_svc_type char(2),
    pr12_svc_id char(2),
    pr12_supp_svc_code varchar(2),
    pr12_sup_svc_ac_cd char(1),
    pr12_radio_channel char(1),
    pr12_transpry_ind varchar(1),
    pr12_msc_id varchar(1),
    pr12_loc_id varchar(1),
    pr12_chrg_scheme char(2),
    pr12_disc_sch_ind varchar(1),
    pr12_dest_ind char(1),
    pr12_other_amt varchar(10),
    pr12_gsm_opr_code varchar(5),
    pr12_tot_chg_sur varchar(10),
    pr12_oth_amt_sur varchar(10),
    pr12_brand_vol varchar(16),
    pr12_filler_1 varchar(2),
    pr12_new_pr_schm char(1),
    pr12_event_ind varchar(1),
    pr12_mob_pager_ind varchar(1),
    pr12_rerated_type char(3),
    pr12_service_type char(2),
    pr12_service_code char(2),
    pr12_chrged_item char(1),
    pr12_call_type char(2),
    pr12_norm_call_num varchar(18),
    pr12_filler_2 varchar(9),
    country_name varchar(30),
    operator_name varchar(30),
    country_code varchar(80)
  );

