drop table if exists "informix".st_mobama ;
create table "informix".st_mobama 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    subscriber_a_num varchar(20),
    date_of_call char(8),
    service_type char(2),
    service_id varchar(2),
    supp_svc_code char(2),
    first_loc_area_cd char(5),
    part_cdr_rec_num char(1),
    answer_time char(6),
    disconnect_time char(6),
    charge_duration char(6),
    call_class char(2),
    charge_ind char(1),
    call_direction char(1),
    subscriber_a_class char(2),
    filler1 varchar(3),
    multimedia_call char(1),
    filler2 varchar(2),
    midnight_pass char(1),
    phase_recovery char(1),
    subscriber_b_num varchar(24),
    subscriber_b_cat char(2),
    call_rec_type char(1),
    hot_billing_ind char(1),
    subscriber_a_imsi varchar(15),
    terminate_reason varchar(5),
    srvcc_indicator varchar(1),
    srvcc_date varchar(8),
    srvcc_time varchar(6),
    mobile_roaming_num varchar(18),
    call_seq_num varchar(6),
    msc_id char(1),
    mrtf_invocation char(1),
    filler3 varchar(1),
    type_of_subscriber char(1),
    disconnect_party char(1),
    filler4 varchar(1),
    operator_code char(1),
    channel_coding char(1),
    isdn_data_rate char(1),
    filler5 varchar(1),
    in_marking char(1),
    imei varchar(15),
    incoimg_route varchar(7),
    outgoing_route varchar(7),
    xcli_ind char(1),
    filler6 varchar(9),
    omei_sw_version char(2),
    filler7 varchar(14),
    dial_num varchar(24),
    plus_key_ind char(1),
    prepaid_svc_ind char(1),
    filler8 varchar(3),
    net_call_ref varchar(12),
    call_chrg varchar(5),
    cdr_rec_seq_num varchar(6),
    filler9 varchar(26),
    redirect_num varchar(20),
    filler10 varchar(20),
    oth_subscriber_num varchar(20),
    redirect_counter varchar(1),
    filler11 varchar(2),
    first_cell_id varchar(10),
    last_cell_id varchar(10),
    last_lac varchar(5),
    filler12 varchar(209)
  );

