drop table if exists "informix".st_mcs ;
create table "informix".st_mcs 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    rec_type char(1),
    file_type char(1),
    file_format char(1),
    traffic_type char(2),
    exchange_id char(2),
    net_serv_id varchar(21),
    net_serv_line_num char(4),
    date_of_call char(8),
    time_of_call char(6),
    dest_code char(7),
    route_code varchar(4),
    called_num varchar(24),
    calling_num varchar(21),
    exchg_code char(2),
    creation_ind char(1),
    counter_ind char(1),
    ref_num varchar(8),
    loc_outpymt_ind char(1),
    exchg_serial_num varchar(12),
    filler varchar(15),
    ind_area varchar(40),
    vpg31_dura varchar(10),
    vpg31_svc_type char(2),
    vpg31_inf_fee_ngst varchar(6),
    vpg31_svc_fee_ngst varchar(6),
    vpg31_st_rev_gst varchar(6),
    vpg31_st_rev_ngst varchar(6),
    vpg31_opr_percnt varchar(6),
    vpg31_start_date varchar(8),
    vpg31_end_date varchar(8),
    vpg31_prod_code varchar(5),
    vpg31_rev_itm_cd varchar(3),
    vpg31_bear_svc_ind varchar(1),
    vpg31_pac_ind varchar(1),
    vpg31_filler varchar(23)
  );

