drop table if exists "informix".stream_cdr ;
create table "informix".stream_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    provider_id varchar(10),
    provider_nm varchar(70),
    cust_id varchar(10),
    cust_nm varchar(40),
    cust_addr1 varchar(40),
    cust_addr2 varchar(40),
    cust_city varchar(40),
    cust_state varchar(10),
    cust_county varchar(40),
    cust_country varchar(50),
    host_id varchar(10),
    host_first_nm varchar(20),
    host_last_nm varchar(40),
    host_addr1 varchar(40),
    host_addr2 varchar(40),
    host_city varchar(40),
    host_state varchar(10),
    host_county varchar(40),
    host_country varchar(50),
    host_phone varchar(30),
    host_email varchar(70),
    order_id varchar(10),
    call_date char(10),
    call_time char(12),
    sched_sites char(10),
    call_type varchar(40),
    call_title varchar(60),
    passcode varchar(20),
    modertor_cd varchar(20),
    arranger_nm varchar(60),
    arranger_phone varchar(30),
    tot_minutes integer,
    tot_parti integer,
    inv_id varchar(10),
    inv_subtot decimal(17,4),
    inv_vat decimal(17,4),
    inv_tot decimal(17,4),
    parti_seq_nbr varchar(10),
    parti_name varchar(40),
    parti_phone varchar(30),
    parti_perminchg decimal(17,4),
    parti_starttime varchar(30),
    parti_minutes integer,
    parti_serv_used varchar(200),
    parti_setup_chg decimal(17,4),
    parti_tot decimal(17,4),
    pref_title_1 varchar(40),
    pref_value_1 varchar(70),
    pref_title_2 varchar(40),
    pref_value_2 varchar(70),
    pref_title_3 varchar(40),
    pref_value_3 varchar(70),
    pref_title_4 varchar(40),
    pref_value_4 varchar(70)
  );

