drop table if exists "informix".tap2_moc_mtc ;
create table "informix".tap2_moc_mtc 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    rec_type smallint not null ,
    chain_ref decimal(6,0),
    imsi char(15),
    imei decimal(16,0),
    mod_ind char(1),
    type_of_number char(1),
    numbering_plan char(1),
    called_number varchar(21,1),
    service_type char(1),
    service_code char(2),
    dual_serv_type char(1),
    dual_serv_code char(2),
    radio_chnl_req char(1),
    radio_chnl_used char(1),
    transparency_ind char(1),
    ss_evnt_actcd_1 char(1),
    ss_evnt_sscd_1 char(2),
    ss_evnt_actcd_2 char(1),
    ss_evnt_sscd_2 char(2),
    ss_evnt_actcd_3 char(1),
    ss_evnt_sscd_3 char(2),
    ss_evnt_actcd_4 char(1),
    ss_evnt_sscd_4 char(2),
    ss_evnt_actcd_5 char(1),
    ss_evnt_sscd_5 char(2),
    msc_id varchar(15,1),
    location_area decimal(5,0),
    cell_id decimal(5,0),
    mobstn_classmark smallint,
    charge_start_dtm datetime year to second,
    utc_timeofstcode char(1),
    chargeable_units decimal(6,0),
    data_vol_ref decimal(6,0),
    charge_sdr decimal(9,3),
    charged_item char(1),
    tax_ratecd smallint,
    exchange_ratecd char(1),
    dest_network char(6),
    exchange_rate decimal(19,9) not null ,
    utc_offset char(5) not null ,
    originating_ntwork varchar(20)
  );

