drop table if exists "informix".tap3_cdr ;
create table "informix".tap3_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    rec_type smallint not null ,
    imsi varchar(30),
    msisdn varchar(30),
    called_num varchar(30),
    dial_digits varchar(30),
    cl_time_stamp varchar(20),
    utc_timeofstcode smallint,
    cl_tot_duration decimal(13,0),
    rec_entity_code char(1),
    location_area decimal(5,0),
    cell_id decimal(5,0),
    imei decimal(16,0),
    tel_serv_code char(2),
    transpare_ind char(1),
    charged_item char(1),
    exch_rate_code char(1),
    call_type_lv1 integer,
    call_type_lv2 integer,
    call_type_lv3 integer,
    disc_code decimal(5,0),
    disc_amt decimal(12,3),
    disctable_amt decimal(12,3),
    charge_type char(2),
    charge_amt decimal(12,3),
    charge_units integer,
    charged_units integer,
    tax_code decimal(5,0),
    tax_value decimal(12,3),
    taxable_amt decimal(12,3),
    calling_num varchar(30),
    loc_currency varchar(10),
    tap_currency varchar(10),
    tap_decim_pl integer,
    sdr_aud_rate decimal(10,6),
    utc_timeofst char(5),
    be_serv_code char(2),
    service_type varchar(10),
    service_code char(2),
    supplserv_act char(2),
    supplserv_cd char(2),
    pdpaddress varchar(120),
    accesspointn varchar(60),
    net_init_pdp varchar(20),
    charging_id varchar(60),
    datavol_in integer,
    datavol_out integer,
    home_bid varchar(50),
    home_location varchar(150),
    originating_ntwork varchar(20)
  );

