drop table if exists "informix".tata_cdr ;
create table "informix".tata_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    call_leg_id varchar(120,37),
    conference_id varchar(120,36),
    host_ent_id varchar(120,36),
    host_ent_nm varchar(120,36),
    host_gma_id varchar(120,36),
    host_gma varchar(120,36),
    host_name varchar(120),
    call_direction varchar(20),
    parti_enpo_id varchar(80),
    parti_enpo_nm varchar(80),
    parti_number varchar(120),
    parti_dial_num varchar(80),
    parti_ent_id varchar(80),
    parti_ent_nm varchar(80),
    parti_gma_id varchar(80),
    parti_gma varchar(80),
    parti_exch_id varchar(80),
    parti_exch_nm varchar(80),
    parti_enpotype varchar(80),
    parti_equitype varchar(80),
    enpo_man_type varchar(80),
    start_dt varchar(20),
    end_dt varchar(20),
    leg_duration integer,
    ivrcl_duration integer,
    screens_num integer,
    media_type varchar(20,5),
    sched_title varchar(80),
    transport varchar(20,8),
    conferencetype varchar(20),
    dial_prefix varchar(20),
    serv_offer_nm varchar(80),
    usage_model varchar(80),
    parti_country varchar(120),
    dial_access_type varchar(120)
  );

