drop table if exists "informix".tata_comm ;
create table "informix".tata_comm 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_type char(1),
    organization varchar(20),
    product varchar(50),
    traffic_direct char(1),
    origin_country varchar(100),
    dest_country varchar(100),
    city varchar(100),
    voice_or_data char(1),
    call_window char(2),
    called_number varchar(64),
    date_of_call char(10),
    time_of_call char(8),
    duration_sec decimal(13,0),
    rate_by_call decimal(13,4),
    term_fee decimal(13,4),
    transit_fee decimal(13,4),
    call_amt decimal(15,4),
    currency varchar(10),
    call_id varchar(20),
    process_flag char(1),
    gmt_seiz_date char(10),
    gmt_seiz_time char(8),
    gmt_disc_date char(10),
    gmt_disc_time char(8),
    true_conv_dur decimal(13,0),
    serv_class_code char(1),
    mobil_flag char(1),
    outpulse_num varchar(100),
    circuit varchar(80),
    ext_cust_ref varchar(200),
    host_id varchar(120),
    conference_id varchar(80),
    cfc_a_country varchar(80),
    cfc_a_dest_cd varchar(80),
    cfc_a_pricing varchar(80),
    cfc_no_tollfee varchar(80),
    cust_contract varchar(80),
    site_name varchar(80),
    site_url varchar(200),
    webex_site_id varchar(80),
    conference_key varchar(200),
    mtg_name varchar(80),
    mtg_type varchar(20),
    host_tm_zone varchar(20),
    user_name varchar(100),
    service_id varchar(100),
    division varchar(100),
    department varchar(100),
    project varchar(100),
    other varchar(100)
  );

