drop table if exists "informix".tclvisp_cdr ;
create table "informix".tclvisp_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    tcl_batch varchar(20) not null ,
    serv_provider varchar(80),
    acct_id varchar(20),
    acct_fkey varchar(60),
    acct_nm varchar(80) not null ,
    pack_def_id varchar(20),
    pack_def_nm varchar(120),
    pack_id varchar(20),
    serv_id varchar(20),
    rating_cd varchar(80),
    trans_id varchar(30),
    tcl_date datetime year to second not null ,
    description varchar(200),
    unit decimal(15,7),
    unit_price decimal(12,6),
    unit_tax decimal(12,6),
    total_amt decimal(12,6),
    usage_class varchar(30),
    usage1 varchar(30),
    usage2 varchar(30),
    usage3 varchar(30),
    usage4 varchar(30),
    usage5 varchar(30),
    custom1 varchar(80),
    custom2 varchar(80),
    custom3 varchar(80),
    custom4 varchar(80),
    custom5 varchar(80),
    reserved1 varchar(80),
    reserved2 varchar(80),
    reserved3 varchar(80),
    reserved4 varchar(80),
    reserved5 varchar(80)
  );

