drop table if exists "informix".tel4g_cdr ;
create table "informix".tel4g_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    p1_part_type char(2),
    p1_spnum_address varchar(20),
    p1_spnum_ntw_pkey char(5),
    p1_spnum_num_pkey char(5),
    p1_spnum_num_type char(1),
    p1_spnum_usr_pf_id char(1),
    p1_spprt_address varchar(20),
    p1_spprt_num_pkey char(4),
    p1_ntelm_address varchar(20),
    p1_ntelm_ntw_pkey char(5),
    p1_ntelm_num_pkey char(5),
    p1_opnum_address varchar(50),
    p1_opnum_num_pkey varchar(5),
    p1_opnum_num_type char(1),
    p1_opnum_usr_pf_id char(1),
    p1_record_id_exorg char(2),
    p1_call_dest char(2),
    p1_home_country_cd char(2),
    p1_home_ntw_code char(4),
    p1_home_ntw_pkey char(5),
    p1_opnnm_address varchar(25),
    p1_opnnm_num_pkey char(5),
    p1_basic_call_type char(2),
    p1_basic_chrg_char char(1),
    p1_rout_im_ex_mode char(1),
    p1_rout_priority char(3),
    p1_inistart_offset varchar(6),
    p1_inistart_times varchar(14),
    p1_service_class char(4),
    p1_udr_ref_num varchar(9),
    p1_record_idn_id varchar(20),
    p1_spare2 varchar(20),
    p1_spare3 varchar(20),
    p1_spare4 varchar(20),
    p1_spare5 varchar(20),
    p1_spare6 varchar(20),
    p1_spare7 varchar(20),
    p1_spare8 varchar(20),
    p1_spare9 varchar(20),
    p1_part_separator char(1),
    p2_part_type char(2),
    p2_calltp_calltype varchar(2),
    p2_calltp_flw_cltp char(1),
    p2_calltp_xfileind char(1),
    p2_cameld_address varchar(20),
    p2_cameld_num_plan char(5),
    p2_cameld_num_type char(1),
    p2_camels_address char(1),
    p2_camels_num_plan varchar(1),
    p2_camels_num_type varchar(1),
    p2_cause_forward char(2),
    p2_data_volume varchar(20),
    p2_data_uom_pkey char(4),
    p2_duration_volume varchar(10),
    p2_duration_uom_pk char(3),
    p2_message_volume char(2),
    p2_message_uom_pk char(3),
    p2_remark_remark varchar(20),
    p2_routnum_address varchar(20),
    p2_routnum_numplan char(5),
    p2_sploc_address varchar(30),
    p2_sploc_num_plan varchar(5),
    p2_srvc_action_cd char(1),
    p2_srvc_vas_code varchar(1),
    p2_start_tm_offset varchar(6),
    p2_start_tm_times varchar(14),
    p2_tariff_sn_pkey varchar(5),
    p2_tariff_usage_id varchar(6),
    p2_tariff_zn_pkey varchar(15),
    p2_tariff_zp_pkey varchar(15),
    p2_tech_part_rectp char(1),
    p2_tech_prepay_ind char(1),
    p2_tech_sc_pkey char(3),
    p2_tech_sc_code char(1),
    p2_tech_term_ind char(1),
    p2_tech_ws_prep_id char(1),
    p2_tariff_zn_ws_pk varchar(20),
    p2_tariff_zp_ws_pk varchar(20),
    p2_spare4 varchar(20),
    p2_remark_reasonid varchar(32),
    p2_remark_reasonpk varchar(10),
    p2_part_separator char(1),
    chg_phone_num varchar(63),
    chg_start_dt datetime year to second,
    chg_end_dt datetime year to second,
    chg_tot_amt decimal(18,10)
  );

