drop table if exists "informix".tel_de_ser ;
create table "informix".tel_de_ser 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    sp_code char(3),
    cust_prod_item char(10),
    ebill_file_id char(8),
    pbi char(8),
    bec char(8),
    inv_arrange_id char(10),
    serv_arrange_id char(10),
    service_num char(29),
    prod_action_code char(1),
    po_num char(16),
    prod_eff_date char(10),
    unit_rate decimal(15,7),
    qty decimal(5,2),
    ord_neg_rate char(1),
    bill_trans_desc char(50),
    prod_desc_1 char(30),
    prod_desc_2 char(30),
    prod_desc_3 char(30),
    data_serv_type char(4),
    bandwidth char(10),
    charge_zone char(25),
    serv_loc_1 char(60),
    serv_loc_2 char(60),
    a_end_serv_num char(19),
    a_end_dlci char(4),
    a_end_cir char(7),
    a_end_vpi char(4),
    a_end_vci char(5),
    b_end_serv_num char(19),
    b_end_dlci char(4),
    b_end_cir char(7),
    b_end_vpi char(4),
    b_end_vci char(5)
  );

