drop table if exists "informix".tel_mi_se ;
create table "informix".tel_mi_se 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    inv_arrange_id char(10),
    bill_issue_dt date,
    doc_ref_num char(10),
    inv_rec_seq_num decimal(9,0),
    section_type char(2),
    line_type char(1),
    glo_itm_ref_num char(7),
    inv_class_desc char(30),
    service_num char(29),
    quantity decimal(10,0),
    bill_trans_desc char(50),
    trans_type_desc char(25),
    trans_type_code char(1),
    start_dt date,
    end_dt date,
    summ_grs_amt_ex decimal(14,4),
    summ_net_amt_ex decimal(14,4),
    gst_amt decimal(14,4),
    summ_price_incl decimal(14,4),
    service_locn1 char(30),
    service_locn2 char(30),
    service_locn3 char(30),
    service_locn4 char(30),
    purch_ord_num char(16),
    unit_rate_incl decimal(18,7) 
        default 0.0000000 not null ,
    pbi char(8),
    bec char(8),
    svc_type_desc char(30),
    svc_num_label char(30),
    data_svc_type char(4),
    bandwidth char(10),
    charge_zone char(25),
    a_end_svc_num char(19),
    a_end_multi char(18),
    b_end_svc_num char(19),
    b_end_multi char(18),
    line_speed char(10)
  );

