drop table if exists "informix".tel_smdr ;
create table "informix".tel_smdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_cd char(2),
    cust_group_num char(3),
    orig_type char(1),
    orig_id char(12),
    info_digits char(2),
    console_nun char(2),
    sub_group char(1),
    term_type char(1),
    term_id char(12),
    route_info char(1),
    cl_date char(3),
    cl_time char(6),
    elapsed_time char(6),
    orig_feat_cd char(1),
    term_feat_cd char(1),
    cl_digits char(12),
    cl_digit_ext char(18),
    d5_record_cd char(2),
    digit_outpul char(29),
    digit_missing char(1),
    d6_record_cd char(2),
    rectype char(1),
    spare char(1),
    acct_auth_cd char(14),
    phone_num varchar(63),
    phone_num_desc varchar(120),
    num_called_desc varchar(120),
    cl_start_dt datetime year to second,
    orig_type_desc varchar(90),
    term_type_desc varchar(90),
    event_ind char(10),
    cust_group_id integer,
    cust_clli_name varchar(20)
  );

