drop table if exists "informix".tnz_cdr_chg ;
create table "informix".tnz_cdr_chg 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    record_type char(2),
    acct_num decimal(20,0),
    statement_dtm datetime year to second,
    inv_component decimal(13,0),
    service_id varchar(50),
    chg_from_dtm datetime year to second,
    chg_to_dtm datetime year to second,
    chg_date_dtm datetime year to second,
    quantity decimal(10,0),
    durn_sec decimal(10,0),
    reference varchar(50),
    billing_desc varchar(255),
    calltype char(2),
    jurisdiction char(1),
    ratebasis char(3),
    spotcode char(5),
    costsource varchar(50),
    amt_excl decimal(16,4),
    amt_incl decimal(16,4),
    circuit_type varchar(50),
    circuit_bar_num varchar(50),
    circuit_from varchar(50),
    circuit_to varchar(50),
    circuit_compdesc varchar(50),
    phone_called varchar(50),
    long_line_desc varchar(75),
    icms_cust_num decimal(10,0),
    circuit_number varchar(10),
    account_name varchar(80),
    clear_service_id varchar(50),
    excess_usage varchar(50),
    product_id varchar(50),
    generic_1 varchar(50),
    generic_2 varchar(50),
    generic_3 varchar(50),
    generic_4 varchar(50),
    generic_5 varchar(50),
    generic_6 varchar(50),
    oot_num decimal(10,0),
    wsp_ref varchar(100),
    add_info varchar(255),
    sale_term char(3),
    prod_amtchg_fl varchar(20),
    product_name varchar(80),
    lastpribook_upd varchar(10)
  );

