drop table if exists "informix".tzlocal_cdr ;
create table "informix".tzlocal_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    account_number varchar(10),
    billing_number varchar(10),
    reassignment_lvl char(1),
    bill_digits_ein char(1),
    bill_digits_std char(1),
    from_number varchar(10),
    to_number varchar(10),
    to_cell varchar(5),
    connect_hour char(2),
    connect_min char(2),
    connect_sec char(2),
    conversation_min varchar(5),
    conversation_sec varchar(3),
    jurisdiction char(2),
    rate_period char(1),
    call_type char(2),
    usp_adv_print char(1),
    usp_adv_extract char(1),
    charge_amount varchar(9),
    member_name varchar(10),
    serial_number varchar(10),
    vpn_acct_code varchar(5),
    answer_time varchar(3),
    feature_flag1 char(1),
    feature_flag2 char(1),
    feature_flag3 char(1),
    feature_flag4 char(1),
    feature_flag5 char(1),
    agent_number varchar(3),
    vpn_direction char(1),
    service_ref varchar(10),
    centre_id char(2),
    charge_basis_cd varchar(5),
    rate_class char(2),
    call_date varchar(9),
    spare1 char(1),
    spare2 char(2)
  );

