drop table if exists "informix".veda_indiv_enq ;
create table "informix".veda_indiv_enq 
  (
    request_id integer not null ,
    salutation_title varchar(15),
    first_name varchar(15),
    middle_name varchar(15),
    last_name varchar(71),
    date_of_birth char(10),
    gender char(1),
    resident_country varchar(64),
    resident_status varchar(32),
    id_type_code varchar(32),
    id_description varchar(32),
    id_expiry_date char(10),
    id_issue_cntrycd char(2),
    id_number char(10),
    cur_propertyname varchar(64),
    cur_unit_no char(5),
    cur_street_no char(8),
    cur_street_name varchar(25),
    cur_street_type char(3),
    cur_suburb varchar(22),
    cur_state char(3),
    cur_post_code char(4),
    cur_country_code char(2),
    time_at_cur_addr smallint,
    prv_propertyname varchar(64),
    prv_unit_no char(5),
    prv_street_no char(8),
    prv_street_name varchar(25),
    prv_street_type char(3),
    prv_suburb varchar(22),
    prv_state char(3),
    prv_post_code char(4),
    prv_country_code char(2),
    time_at_prv_addr smallint
  );

