drop table if exists "informix".vf_cdr ;
create table "informix".vf_cdr 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    charge_party varchar(18),
    non_charge_party varchar(18),
    category char(2),
    disc_category char(1),
    tcom_start_dtm datetime year to second,
    charge_durn interval hour to second,
    nt_free_cl_code char(1),
    tar_class_code char(18),
    whl_price decimal(8,3),
    nt_non_disc decimal(8,3),
    nt_batch_num integer,
    nt_batch_suff integer,
    chg_party_ind char(2),
    rerouting_ind char(1),
    network_code char(2),
    switch_id char(2),
    other_batch char(6),
    retail_price decimal(8,3),
    forced_proc_ind char(1),
    free_period_ind char(1),
    origin char(1),
    tariff_type char(1),
    transmisn_type char(1),
    subscrptn_type char(1),
    subscrptn_tpprfx char(1),
    rtl_non_disc decimal(8,3),
    whl_book_num integer,
    whl_book_type char(1),
    rtl_book_num integer,
    rtl_book_type char(1),
    cause_for_fwd char(2),
    country_orig char(3),
    data_volume decimal(9,0),
    nt_charge_method char(1),
    nt_cl_sv_type char(2),
    nt_cl_sv_code char(2),
    nt_cl_mod_code char(2),
    advice_of_chg char(1),
    telecom_dir char(2),
    nt_deb_cred char(1),
    mobile_stn_class char(1),
    call_ref varchar(22),
    lcl_call_st_dtm datetime year to second,
    nt_timezone_id char(4),
    season_id char(1),
    imei char(15),
    whl_price_prelyl decimal(8,2),
    whl_lyl_disc decimal(8,3),
    lyl_disc_perc decimal(8,3),
    rtl_price_prelyl decimal(8,3),
    rtl_lyl_disc decimal(8,3),
    rtl_post_lyl decimal(8,3),
    nt_cl_orig char(5),
    super_on_net varchar(4),
    camel_ref varchar(16),
    cellid_sae varchar(5),
    indicator_2g3g char(1)
  );

