drop table if exists "informix".vf_prepaid ;
create table "informix".vf_prepaid 
  (
    nt_file_num integer not null ,
    nt_file_rec_num integer not null ,
    customer_no char(8),
    inv_number varchar(8),
    curr_code char(4),
    src_country char(3),
    src_network char(2),
    dest_country char(3),
    tax_treatment char(1),
    acct_type char(1),
    imsi varchar(15),
    charge_party varchar(11),
    tcom_start_dtm datetime year to second,
    non_charge_party varchar(24),
    xfer_batch_num integer,
    xfer_batch_suff decimal(2,0),
    country_code char(3),
    network_code char(2),
    chg_batch_no char(6),
    switch_id char(2),
    charge_durn interval second(6) to second,
    tar_class_code varchar(25),
    nt_cl_sv_type char(2),
    nt_cl_sv_code char(2),
    nt_cl_mod_code char(2),
    disc_category char(1),
    acct_grp char(1),
    whl_price decimal(11,3),
    conv_whl_price decimal(11,3),
    non_disc decimal(11,3),
    category char(2),
    transmisn_type char(1),
    nt_free_cl_code char(1),
    telecom_dir char(2),
    whl_book_type char(1),
    whl_book_num decimal(3,0),
    last_exch_id varchar(16),
    cause_for_fwd char(2),
    cl_type_code decimal(2,0),
    mobile_stn_class char(1),
    exch_rate decimal(12,6),
    lcl_call_st_dtm datetime year to second,
    nt_timezone_id char(4),
    subscrptn_type char(1),
    imei varchar(15),
    location_code varchar(4),
    term_reason varchar(8),
    oth_party_num varchar(15),
    first_cell_id varchar(5),
    last_cell_id varchar(5),
    mth_bundle_used decimal(8,0),
    call_bundle_used decimal(8,0),
    bundle_type char(2),
    whl_price_prebun decimal(11,3),
    whl_price_prelyl decimal(11,3),
    imsi2 varchar(15),
    call_ref varchar(22),
    whls_bill_mth decimal(2,0),
    chg_party_ind char(1),
    chg_method char(1),
    sdr_non_disc decimal(9,0),
    forced_proc char(1),
    orig_price decimal(11,3),
    mod_ind char(1),
    type_of_number char(10),
    num_plan_id char(1),
    season_id char(1),
    vat_type char(2)
  );

